def a = "aaa"

pipeline{
  agent any
  environment {
    a = "bbb"
  }
  stages{
    stage('Test'){
      steps{
	      sh """
          echo $a
          echo ${a}
          echo ${env.a}
        """
      }
    }
  }
}
