def a = "aaa"

def getGitBranchName() {
    return scm.branches[0].name
}

pipeline {
  agent any
  environment {
    a = "bbb"
  }
  stages{
    stage('Test') {
      steps{
        script {
          def env=getGitBranchName()
        }
	      sh """
          echo $a
          echo ${a}
          echo ${env.a}
          echo ${env.BRANCH_NAME}
          echo ${env}
        """
      }
    }
  }
}